[build]
  command = "npm run build && npm run export"
  publish = "out"
  
# Handle Next.js routing with authentication protection
[[redirects]]
  from = "/*/tests/couple-compatibility"
  to = "/*/auth?returnUrl=:splat"
  status = 302
  force = false
  conditions = {Cookie = "!firebase-auth-token"}
  
[[redirects]]
  from = "/*/tests/feedback-360"
  to = "/*/auth?returnUrl=:splat"  
  status = 302
  force = false
  conditions = {Cookie = "!firebase-auth-token"}

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Next.js specific settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static file caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"